# ===============================
# Scene / audio
# ===============================
fs: 24000 # don't change this, since RIRs are simulated at this sampling rate
scene_len_sec: 10.0
scene_len: 240000   # fs * scene_len_sec

min_sources: 3
max_sources: 5

max_overlap: 2
max_tries: 2000

min_event_dur_sec: 1.0
max_event_dur_sec: 5.0

rms_thresh: 1.0e-3
min_angular_sep_deg: 30.0

n_diffuse_sources: 1
fg_to_diffuse_snr_db_range: [3, 20]  # SNR range for fg to diffuse sources (in dB)
mixing_time_sec: 0.05  # diffuse sources will use RIRs from this time onwards to ensure no direct and early reflections are included
# ===============================
# Dataset paths 
# ===============================
split: "train" # uses only train files from FSD50k_FMA dataset. if you set it to test uses only test files. If you set it to None, it uses all files.
               # check how I am using this in case you want to extend it for new datasets.

vctk_dir: "/media/partha/LaCie/datasets/VCTK_corpus-0.92_splits/train/flac"
musdb_dir: "/path/to/music_dataset"

fsd50k_fma_dir: "/media/partha/LaCie/datasets/sound_event_datasets/FSD50K_FMA"
fsd50k_fma_exclude_classes:
  - maleSpeech
  - femaleSpeech
  - music
  - musicInstrument

nigens_dir: "/media/partha/LaCie/datasets/iterative_slot_learning/nigens_dataset_splits"
nigens_exclude_classes:
  - maleSpeech
  - femaleSpeech
  - piano
  - general 
  - fire 

freesound_dir: "/media/partha/LaCie/datasets/freesound_unverified"  # dont use this if you want good labels. Use for un/self-supervised learning.
                                                                    # This is a dataset I downloaded with unverified labels. Use with caution.

background_dir: "/media/partha/LaCie/datasets/wham_noise/tr" # For diffuse sources

# ===============================
# Dataset mode
# ===============================
dataset_mode: 
  - "fsd50k_fma"
  - "vctk"
  - "nigens"
  - "freesound"
  #- "musdb"

# ===============================
# Simulation scale
# ===============================
hoa_order: 1
mixtures_per_room: 10
n_rooms: 10

# ===============================
# Paths
# ===============================
rir_dir: "/media/partha/LaCie/simulated_rirs_test_hoa_order_5"
out_dir: "/media/partha/LaCie/foa_simulated_mixtures/train"